FROM xrsec/php:latest
LABEL maintainer="xrsec"
LABEL mail="troy@zygd.site"
ARG TARGETPLATFORM

RUN curl -fsSL https://code-server.dev/install.sh | sh \
    # && cp /www/bak/ssl_cert/vscode.crt /root/.local/share/code-server/localhost.crt \
    # && cp /www/bak/ssl_cert/vscode.key /root/.local/share/code-server/localhost.key
    && cp /www/bak/resources/favicon.svg /usr/lib/code-server/src/browser/media/favicon-dark-support.svg \
    && cp /www/bak/resources/favicon.ico /usr/lib/code-server/src/browser/media/favicon.ico \
    && cp /www/bak/resources/favicon.svg /usr/lib/code-server/src/browser/media/favicon.svg \
    && cp /www/bak/resources/favicon.png /usr/lib/code-server/src/browser/media/pwa-icon-192.png \
    && cp /www/bak/resources/favicon.png /usr/lib/code-server/src/browser/media/pwa-icon-512.png \
    && cp /www/bak/resources/favicon.png /usr/lib/code-server/src/browser/media/pwa-icon.png \
    && sed -i "s/code-server/Visual Studio Code/g" /usr/lib/code-server/src/browser/media/manifest.json \
    && sed -i "s/Run editors on a remote server./Copyright (C) 2021 Microsoft. All rights reserved/g" /usr/lib/code-server/src/browser/media/manifest.json

ENTRYPOINT ["/vscode.sh"]

EXPOSE 22 5050 5051 8765 31000 31001 31002 31003

ENV TZ='Asia/Shanghai'
ENV LANG 'zh_CN.UTF-8'

STOPSIGNAL SIGQUIT

CMD ["/vscode.sh"]
