name: Code-Server Update

 # 触发条件
on:
  push:
  watch:
    types: [started]
  schedule:
    - cron: '0 0 * * *'

jobs:
  Curl-Code-Server:
     runs-on: ubuntu-latest
     steps:
       - name: 'xecute command'
         env:
           Github_Api: https://api.github.com/repos
           Github_User: cdr
           Github_Repo: code-server
         run: curl $Github_Api/$Github_User/$Github_Repo/releases/latest | grep "tag_name" | cut -d '"' -f 4