name: Docker Code Server Update
  
on:
  push

jobs:
  push_to_registry:
    name: Docker Code Server Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: version_checking
        run: |
          python .github/code-server_version/version_checking.py
          uname -p
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Run commands
        id: runcmd
        with:
          arch: armv7
          distro: ubuntu18.04
          githubToken: ${{ secrets.TOKEN_GITHUB }}
          run: |
            uname -p
            echo ::set-output name=uname::$(uname -a)
      # # update version
      # - name: Update resources
      #   uses: test-room-7/action-update-file@v1
      #   with:
      #       file-path: .github/code-server_version/code-server_version
      #       commit-msg: Update code-server version
      #       github-token: ${{ secrets.TOKEN_GITHUB }}
      # - 
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # - 
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # - 
      #   name: Log in to Docker Hub
      #   uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - 
      #   name: Build and push Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: |
      #       xrsec/vscode:latest
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
