name: Docker Code Server Build
  
on:
  workflow_dispatch:
  repository_dispatch:
    types: [Code_Update_Action]
  schedule:
    - cron:  '0 0 * * MON'

jobs:
  Build_For_Code_Server:
    name: Docker Code Server Build
    runs-on: ubuntu-latest
    steps:
      - 
        name: Private Actions Checkout
        uses: actions/checkout@v5
      - 
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - 
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.11.1
      # - 
      #   name: Code Server Download
      #   run: |
      #     mkdir -p linux/arm64 linux/amd64
      #     wget -O linux/amd64/code-server.rpm `curl https://api.github.com/repos/cdr/code-server/releases/latest | grep "browser_download_url"  | cut -d '"' -f 4 | grep amd64.rpm` --no-cookie --no-check-certificate
      #     wget -O linux/arm64/code-server.rpm `curl https://api.github.com/repos/cdr/code-server/releases/latest | grep "browser_download_url"  | cut -d '"' -f 4 | grep arm64.rpm` --no-cookie --no-check-certificate 
      - 
        name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Docker Login in Gihtub
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.TOKEN_GITHUB }}
      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/code-server:latest
            ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/code-server:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/code-server:cache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/code-server:cache,mode=max
